// The detection-health row (plan § Detection design). Yellow when the content
// script has been mounting on linkedin.com for 2+ days without a comment being
// detected, or when hints keep passing their deadline without a DOM outcome.
// The Report link prefills a GitHub issue with counts and versions — no content.
import { daysBetween, EVENT_LABELS, EVENT_TYPES, toDateKey, type EventType } from '@/src/core';
import type { Health } from '@/src/messaging/protocol';
import { browserName, daysAgo } from './format';

export const ISSUE_URL = 'https://github.com/Phonografik/go-comment/issues/new';
const DAY = 86_400_000;
const STALE_DAYS = 2;
const UNCONFIRMED_LIMIT = 3;

export interface DetectionIssue {
  /** whole days since the last confirmed comment, when one has ever been confirmed */
  daysSinceComment?: number;
  /** every type with a non-zero unconfirmed count */
  unconfirmed: Array<[EventType, number]>;
}

export function detectionIssue(health: Health, now: Date): DetectionIssue | undefined {
  const lastComment = health.lastDetected.c;
  const stale = lastComment !== undefined && health.lastPageLoad - lastComment >= STALE_DAYS * DAY;
  const unconfirmed = EVENT_TYPES.map((t): [EventType, number] => [t, health.unconfirmed[t] ?? 0]).filter(([, n]) => n > 0);
  const noisy = unconfirmed.some(([, n]) => n >= UNCONFIRMED_LIMIT);
  if (!stale && !noisy) return undefined;
  return {
    daysSinceComment: lastComment === undefined ? undefined : daysBetween(toDateKey(new Date(lastComment)), toDateKey(now)),
    unconfirmed,
  };
}

export function issueMessage(issue: DetectionIssue): string {
  if (issue.daysSinceComment !== undefined && issue.daysSinceComment >= STALE_DAYS) {
    return `Last comment detected ${daysAgo(issue.daysSinceComment)}. If you've commented since, detection may be broken.`;
  }
  const n = issue.unconfirmed.reduce((sum, [, count]) => sum + count, 0);
  return `${n} action${n === 1 ? '' : 's'} went unconfirmed. If they happened, detection may be broken.`;
}

/** A prefilled new-issue URL. Carries the selectors version, browser family, and counts. Never content. */
export function reportUrl(issue: DetectionIssue, health: Health, userAgent: string): string {
  const browser = browserName(userAgent);
  const counts = issue.unconfirmed.map(([t, n]) => `${EVENT_LABELS[t].many}=${n}`).join(', ') || 'none';
  const lines = [
    '**Detection health report** (generated by the popup — counts only)',
    '',
    `- selectors: ${health.selectorsVersion || 'unknown'}`,
    `- browser: ${browser}`,
    `- last comment detected: ${issue.daysSinceComment === undefined ? 'never' : daysAgo(issue.daysSinceComment)}`,
    `- unconfirmed: ${counts}`,
    '',
    'What did you do on LinkedIn that was not counted?',
    '',
  ];
  const params = new URLSearchParams({
    title: `Detection: ${browser}, selectors ${health.selectorsVersion || 'unknown'}`,
    body: lines.join('\n'),
    labels: 'detection',
  });
  return `${ISSUE_URL}?${params.toString()}`;
}
